name: Publish to VS Code Marketplace

on:
  release:
    types: [created]

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'webredone' && github.event.release.target_commitish == 'main'

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Package Extension
        run: npx vsce package

      - name: Publish Extension
        run: npx vsce publish -p ${{ secrets.VS_MARKETPLACE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_PAT }}
